--(i) TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2000
SELECT SUM("2000") AS total_debt_2000 FROM IDS_Data

--(ii)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2001
SELECT SUM("2001") AS total_debt_2001 FROM IDS_Data

--(iii)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2002
SELECT SUM("2002") AS total_debt_2002 FROM IDS_Data

--(iv)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2007
SELECT SUM("2007") AS total_debt_2007 FROM IDS_Data

--(v)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2008
SELECT SUM("2008") AS total_debt_2008 FROM IDS_Data

--(vi)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2009
SELECT SUM("2009") AS total_debt_2009 FROM IDS_Data

--(vii)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2013
SELECT SUM("2013") AS total_debt_2013 FROM IDS_Data

--(viii)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2014
SELECT SUM("2014") AS total_debt_2014 FROM IDS_Data

--(ix)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 2015
SELECT SUM("2015") AS total_debt_2015 FROM IDS_Data

--(x)TO COMPUTE THE TOTAL DEBT OWNED BY ALL COUNTRIES IN YEAR 1988
SELECT SUM("1988") AS total_debt_1988 FROM IDS_Data