--(i) TO COMPUTE THE TOTAL NUMBER OF UNIQUE INDICATOR CODE
SELECT COUNT (DISTINCT "Indicator Code") AS total_unique_code FROM IDS_Data
 
--(ii) TO RETRIEVE THE UNIQUE INDICATOR CODE
SELECT DISTINCT "Indicator Code" FROM IDS_Data
