--(i) MAXIMUM DEBT OWED BY EACH COUNTRY IN DESCENDING ORDER FOR 1998
SELECT "Country Name", "Country Code", MAX(CAST("1998" AS INT)) AS MAX_debt_1998 FROM IDS_Data
    GROUP BY "Country Name"
    ORDER BY "MAX_debt_1998" DESC
    
--(ii) MAXIMUM DEBT OWED BY EACH COUNTRY IN DESCENDING ORDER FOR 1999
SELECT "Country Name", "Country Code", MAX(CAST("1999" AS INT)) AS MAX_debt_1999 FROM IDS_Data
    GROUP BY "Country Name"
    ORDER BY "MAX_debt_1999" DESC
    
--(iii) MAXIMUM DEBT OWED BY EACH COUNTRY IN DESCENDING ORDER FOR 2001
SELECT "Country Name", "Country Code", MAX(CAST("2001" AS INT)) AS MAX_debt_2001 FROM IDS_Data
    GROUP BY "Country Name"
    ORDER BY "MAX_debt_2001" DESC
    
--(iv) MAXIMUM DEBT OWED BY EACH COUNTRY IN DESCENDING ORDER FOR 2010
SELECT "Country Name", "Country Code", MAX(CAST("2010" AS INT)) AS MAX_debt_2010 FROM IDS_Data
    GROUP BY "Country Name"
    ORDER BY "MAX_debt_2010" DESC
    
--(v) MAXIMUM DEBT OWED BY EACH COUNTRY IN DESCENDING ORDER FOR 2012
SELECT "Country Name", "Country Code", MAX(CAST("2012" AS INT)) AS MAX_debt_2012 FROM IDS_Data
    GROUP BY "Country Name"
    ORDER BY "MAX_debt_2012" DESC
    
--(vi) MAXIMUM DEBT OWED BY EACH COUNTRY IN DESCENDING ORDER FOR 2015
SELECT "Country Name", "Country Code", MAX(CAST("2015" AS INT)) AS MAX_debt_2015 FROM IDS_Data
    GROUP BY "Country Name"
    ORDER BY "MAX_debt_2015" DESC